# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sinatra', '~> 2.0'

group :development do
  gem 'capybara', '~> 3.12'
  gem 'pry', '~> 0.12.2'
  gem 'pry-byebug', '~> 3.6'
  gem 'rerun'
  gem 'rspec', '~> 3.8'
  gem 'rubocop', '~> 0.60.0'
  gem 'simplecov', '~> 0.16.1'
end
